config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  get "/dashboard", to: "dashboard#show"
  put "/dashboard", to: "dashboard#update"
  patch "/dashboard", to: "dashboard#update"

  get "/information", to: "information#show"
  post "/information", to: "information#create"
  get "/auth/:provider/callback", to: "sessions#create"

  delete "/logout", to: "sessions#destroy", as: "logout_path"
end

app/models/current_user.rb
class CurrentUser
  attr_reader :user

  def initialize(user)
    @user = user
  end

  def starting_path
    if user
      "layouts/main"
    else
      "layouts/login_page"
    end
  end

  def matches
    if user
      "layouts/matches"
    else
      "layouts/empty"
    end
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :user_languages
  has_many :users, through: :user_languages
end

app/models/pair.rb
class Pair < ActiveRecord::Base
end

app/models/pairing.rb
require 'pairr_state_machine'

class Pairing < ActiveRecord::Base
  belongs_to :user, class_name: "User"
  belongs_to :pair, class_name: "User"

  after_initialize do
    self.state ||= Pairing.initial_state
  end

  def self.secret_detractors
    where state: 'secret_detractor'
  end

  def self.secret_admirers
    where state: 'secret_admirers'
  end

  def self.infinite_potentials(user)
    User.find_by_sql([
      'select * from users where
        ( id not in (select user_id from pairings where pair_id = ?)
          and id not in (select pair_id from pairings where user_id = ?)
        )
      ', user.id, user.id
    ])
  end

  def self.for(user1, user2)
    where(user_id: user1.id, pair_id: user2.id).first   ||
      where(user_id: user2.id, pair_id: user1.id).first ||
      new(user: user1, pair: user2, state: initial_state)
  end

  def self.initial_state
    @initial_state ||= PairrStateMachine.new.state
  end

  def true_love?
    state == 'true_love'
  end

  def like
    self.state = PairrStateMachine.new(state.to_sym).like!
    self
  end

  def hate
    self.state = PairrStateMachine.new(state.to_sym).hate!
    self
  end

  def decide(decision)
    decision ? like : hate
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_languages
  has_many :languages, through: :user_languages

  def self.find_or_create_with_oauth(github_hash)
    user = User.find_by(name: github_hash[:login])
    return user if user
    User.create!(name: github_hash[:login]) do |user|
      user.name       = github_hash[:login]
      user.avatar_url = github_hash[:avatar_url]
      user.html_url   = github_hash[:html_url]
      user.save

      user.languages = Language.all
    end
  end

  def self.all_except(user)
    User.where.not(id: user.id)
  end

  def associate_languages(langs)
    langs.each do |lang, bool|
      if !bool.zero?
        lang_id = Language.find_by(name: lang).id
        user_lang = user_languages.where(language_id: lang_id, user_id: id).first
        if user_lang
          user_lang.mark_as_preferred
        end
      else
      end
    end
  end

  def preferred_languages
    user_languages.where(preferred: true).map(&:language)
  end

  def matches
    User.find_by_sql [
      'select * from users where
         (    id in (select user_id from pairings where pair_id = ? and state = "true_love")
           or id in (select pair_id from pairings where user_id = ? and state = "true_love")
         )
      ', id, id
    ]
  end

  def secret_admirers
    Pairing.includes(:user).where(state: 'secret_admirer', pair_id: id).map(&:user)
  end
end

app/models/user_language.rb
class UserLanguage < ActiveRecord::Base
  belongs_to :user
  belongs_to :language

  def mark_as_preferred
    update(preferred: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    CurrentUser.new(User.find_by(id: session[:user_id]))
  end

  helper_method :current_user
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    user      = current_user.user
    @new_user = user.secret_admirers.first || Pairing.infinite_potentials(user).first
    render :show
  end

  def index
    @user = current_user.user
  end

  def update
    user       = current_user.user
    other_user = User.find params['pair_id']
    pairing    = Pairing.for(user, other_user).decide(approval?).tap(&:save!)
    pairing.true_love? and flash[:notice] = "Congrats #{user.name}, you and #{other_user.name} are a good match!"
    redirect_to :back
  end

  private

  def approval?
    params[:_method] == "put"
  end
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  def show
  end

  def create
    user = current_user.user
    parse_params
    lang_ids = params[:information].keys[0..-2].map { |k, v| Language.find_by(name: k).id }
    user.user_languages.where(language_id: lang_ids).each { |ul| ul.update(preferred: true) }
    user.update!(description: params[:information][:about])
    redirect_to root_path
  end


  def parse_params
    params[:information].delete_if{|key, value| value == "0"}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create_with_oauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    if user.description
      redirect_to root_path
      flash[:notice] = "Welcome #{user.name}!"
    else
      redirect_to information_path
      flash[:notice] = "Fill out some basic information before continuing."
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def language_form
    form_for("Languages", url: "/information") do |f|
      Language.all.where(preferred: false).map do |lang|
        f.check_box(lang.name, {}, {multiple: true}, 0)
        f.label(lang.name, lang.name, {multiple: true})
      end
      f.submit
    end
  end
end

app/views/dashboard/index.html.erb
<%= link_to "Find Pairs!", dashboard_path %>

<div id="matches">
<%= render current_user.matches %>
</div>

app/views/dashboard/show.html.erb
<div id="name">
  User's github name: <%= @new_user.name %><br>
</div>
<div id="description">
  User's description: <%= @new_user.description %><br>
</div>
<div id="avatar_url">
  User's github profile pic: <%= image_tag @new_user.avatar_url %><br>
</div>
<div id="langs">
  User's list of desired languages: <% @new_user.preferred_languages.each do |lang| %>
    <%= lang.name %><br>
  <% end %>
</div>

<div class="buttons">
  <%= button_to "Approve!", dashboard_path(pair_id: @new_user.id) , method: :put %>
  <%= button_to "Reject!", dashboard_path(pair_id: @new_user.id) , method: :patch  %>

</div>

app/views/information/show.html.erb
<div id="information">

  <%= form_for("information", url:"/information") do |f| %>
    <% Language.all.each do |l| %>
      <%= f.check_box(l.name, {}) %>
      <%= f.label(l.name, l.name) %>
      <br>
    <% end %>
    <%= f.label("about", "Tell us about yourself") %>
    <%= f.text_field("about", {id: "about",
                     maxlength: 500,
                     size: 75,
                     placeholder: "Favorite text editor, tdd, dsa, rpg character"}) %>
                     <%= f.submit %>
                   <% end %>
                 </div>

app/views/layouts/_empty.html.erb
<h2>You have no matches.</h2>
<h3>Login to get some.</h3>

app/views/layouts/_login_page.html.erb
<div id="login">
  <%= link_to "Login with GitHub", "/auth/github"  %>
</div>

app/views/layouts/_main.html.erb
<%= yield %>

app/views/layouts/_matches.html.erb
  <h3>Your Matches:</h3>
  <% @user.matches.each do |match| %>
    <%= match.name %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pairr</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="card-panel teal lighten-5">
          <%= content_tag :div, msg, id: "flash_#{name}" %>
        </div>
      <% end %>
    </div>

    <%= render current_user.starting_path %>

  </body>
</html>